### ISSUE TITLE
`storage_withdraw` is not refunding storage balance

### ISSUE THREAD

**Issue by andy-haynes** [near/chain-deployed-ui#46]
I’m not getting refunded after calling storage_withdraw but I can’t tell where things are going wrong :thinking_face:

When deploying, I call [storage_deposit](https://testnet.nearblocks.io/txns/5ASsZs68RWRX2qqsJDypTUtx2HTiy5L9JTqdqCuqv6Lc) on the file contract. When deleting the app, I delete storage to the point where the available balance is nearly equal to the total:
```
withdrawing balance {
  'gornt.testnet balance': '105.677779',
  'pfs1.testnet balance': '131.932608',
  'pfs1.testnet storage balance for gornt.testnet': '3.36484/3.36694'
}
```

Then I call [storage_withdraw](https://testnet.nearblocks.io/txns/7rS4GSWGARb8tqBDhUY6ibVU9cE63b7Kzz5tXvtoQBuN?tab=execution) and see that only a fraction of the available balance (0.18665N vs ~3.6N) is refunded. After this call, the deployer account actually loses Near instead of getting the original storage refunded:
```
balance withdrawn {
  'gornt.testnet balance': '105.676335',
  'gornt.testnet balance diff': '-0.001444',
  'pfs1.testnet balance': '131.933006',
  'pfs1.testnet balance diff': '0.000397',
  'pfs1.testnet storage balance for gornt.testnet': '0/0.0021'
}
```

Nothing sticks out as problematic in the method source, though it is worth mentioning I added a null check so that passing a null amount refunds the available funds. However, I was seeing the same behavior when specifying the amount when calling.

I think the key is understanding why storage_withdraw refunded 0.18665N; the transaction clearly went through but why is that the amount being refunded when the ~3.6 was being correctly deducted from the balance?

**Comment by mpeterdev** [comment]
`NearPromise` instances must either be returned or have `.build()` called to execute. For now, we will use `.build()` since we must return the appropriate data for the StorageManagement NEP

**Comment by mpeterdev** [comment]
follow up in #47
